/**
 Players generally sit in a circle. The player designated to go first says the number "1", 
 and each player thenceforth counts one number in turn. However, any number divisible by 'A' e.g. 
 three is replaced by the word fizz and any divisible by 'B' e.g. five by the word buzz. Numbers 
 divisible by both become fizz buzz. A player who hesitates or makes a mistake is either eliminated.

Write a program that prints out the the pattern generated by such a scenario given the values of 
'A'/'B' and 'N' which are read from an input text file. The input text file contains three space 
delimited numbers i.e. A, B, N. The program should then print out the final series of numbers using 
'F' for fizz, 'B' for 'buzz' and 'FB' for fizz buzz. 
 */
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class fizzbuzz {

	public static void main(String[] args) {
		String file = args[0];
		read(file);
		//read("a");
	}

	public static void read(String f) {
		try {
			BufferedReader in = new BufferedReader(new FileReader(f));
			String str;

			while ((str = in.readLine()) != null) {

				System.out.println(process(str));
			}
			in.close();
		} catch (IOException e) {
		}
	}

	private static String process(String str) {
		String s = "";
		String[] st = str.split(" ");
		int a = Integer.parseInt(st[0]);
		int b = Integer.parseInt(st[1]);
		int c = Integer.parseInt(st[2]);
		for (int i = 1; i <= c; i++) {
			if (i % a == 0 && i % b == 0) {
				s += "FB ";
			} else if (i % a == 0) {
				s += "F ";
			} else if (i % b == 0) {
				s += "B ";
			} else {
				s += i + " ";
			}
		}

		return s;
	}

}